replicaCount: 2

image:
  repository: ghcr.io/harishrao9/foodrush
  tag: 20260808080703
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

env:
  APP_ENV: "EKS"
  APP_VERSION: "1.0.0"
  PORT: "3000"

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

probes:
  liveness:
    path: /health
    initialDelaySeconds: 15
    periodSeconds: 20
  readiness:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 10